export const categories = {
  frogs: [
    "/images/frogs/BirgerStrahl.jpg",
    "/images/frogs/ChrisCurry.jpg",
    "/images/frogs/CrystalMcClernon.jpg",
    "/images/frogs/DavidClode.jpg",
    "/images/frogs/EmilyCao.jpg",
    "/images/frogs/KevinGedge.jpg",
    "/images/frogs/OleksandrKuzmin.jpg",
    "/images/frogs/rigel.jpg",
    "/images/frogs/StephenHocking.jpg",
    "/images/frogs/TaychinOlanwichitwong.jpg",
    "/images/frogs/TimothyDykes.jpg",
    "/images/frogs/TimothyDykes2.jpg",
    "/images/frogs/TimoVolz.jpg",
    "/images/frogs/TommyBond.jpg",
    "/images/frogs/ZdenekMachacek.jpg",
    "/images/frogs/ZdenekMachacek2.jpg",
  ],
  bugs: [
    "/images/bugs/BobBrewer.jpg",
    "/images/bugs/BradleyFeller.jpg",
    "/images/bugs/EropKamereb.jpg",
    "images/bugs/EropKamereb2.jpg",
    "images/bugs/HasanAlmasi.jpg",
    "images/bugs/JamesWainscoat.jpg",
    "images/bugs/JasonLeung.jpg",
    "images/bugs/KrzysztofNiewolny.jpg",
    "images/bugs/KrzysztofNiewolny2.jpg",
    "images/bugs/MartinVysoudil.jpg",
    "images/bugs/MaxwellIngham.jpg",
    "images/bugs/MinhTri.jpg",
    "images/bugs/RosieKerr.jpg",
    "images/bugs/StephenHocking.jpg",
    "images/bugs/YuichiKageyama.jpg",
    "images/bugs/YuichiKageyama2.jpg",
  ],
};
